version: "3.9"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: mydbpass

  web:
    build: .
    # These volumes are to allow live editing of the code and auto-restart with nodemon,
    # but when "in production" they become unnecessary:
    volumes:
      - type: bind
        source: ./app/index.ts
        target: /var/app/index.ts
      - type: bind
        source: ./app/api
        target: /var/app/api

    ports:
      - "8000:8000"
    depends_on:
      - db
