version: "3.9"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: mydbpass

  web:
    build: .
    volumes:
      - type: bind
        source: ./app
        target: /var/app

    ports:
      - "8000:8000"
    depends_on:
      - db
